CREATE DOMAIN IF NOT EXISTS interview_type AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS interview_status AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS difficulty_level AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS submission_status AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS jsonb AS VARCHAR(10000);
CREATE DOMAIN IF NOT EXISTS "text[]" AS ARRAY;
